=== desilinguist/ibleu/trunk/demo/mteval-xml-v1.5.dtd
<!--
 History:
 version-XML 1.5:
    added srclang attribute values:
      'Czech'
      'French'
      'German'
      'Spanish'
    added trglang attribute values:
      'Arabic'
      'Czech'
      'Farsi'
      'German'
      'Spanish'
      'Urdu'
    added doc genre attribute values:
      'ps' (prepared speech)
      'wl' (weblog)
      'xx' (unspecified)
 version-XML 1.4:
    added doc genre attribute values:
      'sp' (speech)
      'ed' (editorial)
      'bc' (broadcast conversations)
      'bn' (broadcast news)
      'ng' (newsgroup)
 version-XML 1.3:
    removed tstset 'condition' attribute
    removed tstset 'type' attribute
    updated srclang attribute values (Arabic, Chinese, English, Farsi, Urdu)
    updated trglang attribute values (Chinese, English, French )
 version-XML 1.2:
    added tstset type attribute (one of primary, contrastive1, contrastive2, contrastive3)
    added tstset condition attribute (one of constrained, unconstrained)
    added tstset sysid attribute
    added refset refid attribute
    updated srclang attribute values (Arabic, Chinese, English, Urdu)
    updated trglang attribute values (Chinese, English)
    updated genre attribute values (nw, wb)
    removed doc sysid attribute
    removed srcset trglang attribute
 version-XML 1.1: 
    added French as trglang value
    added Farsi as a srclang value
    added web as a genre value
 version-XML 1.0: move to first XML version of the DTD
-->

<!ENTITY lt     "&#38;#60;">
<!ENTITY gt     "&#62;">
<!ENTITY amp    "&#38;#38;">
<!ENTITY apos   "&#39;">
<!ENTITY quot   "&#34;">

<!ELEMENT mteval (srcset | refset+ | tstset+)>
<!ELEMENT srcset (doc+)>
<!ATTLIST srcset setid CDATA #REQUIRED>
<!ATTLIST srcset srclang (Arabic | Chinese | Czech | English | Farsi | French | German | Spanish | Urdu) #REQUIRED>

<!ELEMENT refset (doc+)>
<!ATTLIST refset setid CDATA #REQUIRED>
<!ATTLIST refset srclang (Arabic | Chinese | Czech | English | Farsi | French | German | Spanish | Urdu) #REQUIRED>
<!ATTLIST refset trglang (Arabic | Chinese | Czech | English | Farsi | French | German | Spanish | Urdu) #REQUIRED>
<!ATTLIST refset refid CDATA #REQUIRED>

<!ELEMENT tstset (doc+)>
<!ATTLIST tstset setid CDATA #REQUIRED>
<!ATTLIST tstset srclang (Arabic | Chinese | Czech | English | Farsi | French | German | Spanish | Urdu) #REQUIRED>
<!ATTLIST tstset trglang (Arabic | Chinese | Czech | English | Farsi | French | German | Spanish | Urdu) #REQUIRED>
<!ATTLIST tstset sysid CDATA #REQUIRED>

<!ELEMENT doc (hl | p | poster | seg)*>
<!ATTLIST doc docid CDATA #REQUIRED>
<!ATTLIST doc genre (bc | bn | ed | ng | nw | sp | ps | wb | wl | xx) #REQUIRED>

<!ELEMENT hl (seg*)>

<!ELEMENT p (seg*)>

<!ELEMENT poster (seg*)>

<!ELEMENT seg (#PCDATA)>
<!ATTLIST seg id CDATA #REQUIRED>

=== desilinguist/ibleu/trunk/demo/small-tst2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mteval SYSTEM "ftp://jaguar.ncsl.nist.gov/mt/resources/mteval-xml-v1.5.dtd">
<mteval>
<tstset setid="newssyscombtest2010" srclang="French" trglang="English" sysid="maryland">
<doc docid="idnes.cz/2009/12/11/76492" genre="nw">
<hl>
<seg id="1"> The lack of snow  concern the hotel </seg>
</hl>
<p>
<seg id="2"> The trails deserted  problem to operators of lifts. </seg>
<seg id="3"> The lack of snow  book their stays in hotels and pensions. </seg>
<seg id="4"> Of this, it is still possible  for all dates in winter, including Christmas and new year. </seg>
</p>
<p>
<seg id="5"> We have a lot of visits  site. </seg>
<seg id="6"> The Internet travel offers prices but dare not commit to reserve for the moment. </seg>
<seg id="7"> And if they call, they ask  there will be snow or mud at Christmas, &quot;said Martin Jandura, operator of Spindl.info. information portal </seg>
</p>
<p>
<seg id="8"> If we want to spend New Year of his dreams to Špindlerův Mlýn, better is no longer hesitate to book. </seg>
<seg id="9"> If the priority is given to economies and that the quality of accommodation only then, we can try to wait a few more days. </seg>
</p>
<p>
<seg id="10"> The Špindler hotel offer for the moment that stays of one week for the new year. </seg>
<seg id="11"> I think that they will try again a moment of the place, but they Cèderont them and accept shorter periods. </seg>
<seg id="12"> And then the number of rooms free will quickly, &quot;said Jandura. </seg>
</p>
<p>
<seg id="13"> The tourism Ingtours Agency of  free beds for all periods of winter. </seg>
<seg id="14"> The week of Christmas we are most concerned for the moment, it is not completely sold. </seg>
<seg id="15"> There are still free, say, half  our offer. </seg>
<seg id="16"> That is why we have already prepared a few last minute Christmas stays cheaper, &quot;said the director of Ingtours Petr Schiefert. </seg>
</p>
<p>
<seg id="17"> The tourism agency of Vrchlabí  new year to Krkonoše, but there are fewer places free. </seg>
<seg id="18"> The first fourteen days of February go well, the remaining winter trips sell moderately. </seg>
</p>
<p>
<seg id="19"> This year, interest for  been negatively influenced by the fact that there is still no snow to Krkonoše. </seg>
<seg id="20"> The people expect that it will start to fall. </seg>
<seg id="21"> Nobody wants to spend the winter untain without snow. </seg>
<seg id="22"> If the trails cover during the week, Christmas also will be complete, &quot;think Schiefert. </seg>
</p>
<p>
<seg id="23"> In contrast, the occupation of the hotel Horizont CI pod Sněžkou is slightly higher than last year. </seg>
<seg id="24"> It was an improvement of almost five percent. </seg>
</p>
<p>
<seg id="25"> We still last few places for the new year as for Christmas. </seg>
<seg id="26"> There is a great interest during the holidays of January of selling well, &quot;inform Karel Rada, Director of best hotel CI. </seg>
</p>
<p>
<seg id="27"> The Omnia Hotel near the parking central Jánské Lázně is also full to eighty percent during the new year period. </seg>
<seg id="28"> On the contrary, half the beds remain empty at Christmas in  Lázně. </seg>
<seg id="29"> This year, we have been pleasantly , where we already have sixty percent of occupation at the moment. </seg>
<seg id="30"> February is a little more low at the moment, but as soon as snow will fall, the interest for the Krkonoše still enlarging certainly indicated the Director of the hotel Omnia, Erik Sporysch. </seg>
</p>
<p>
<seg id="31"> The hotel Krkonoše must not however hope more snow. </seg>
<seg id="32"> Thursday it will more costs and if there are precipitation, they should be snowy mountain. </seg>
<seg id="33"> But by the time should be warm, inform Jiří Jakubský of Hradec station of the Czech Hydrometeorological Institute. </seg>
</p>
</doc>
<doc docid="lidovky.cz/2009/12/10/75519" genre="nw">
<hl>
<seg id="1"> United States: repetition is mother of wisdom </seg>
</hl>
<p>
<seg id="2"> It becomes even comic, conscientious effort with which Barack Obama, President to the reputation of wise, reproduces the strategy of his predecessor on the Afghan question, he considered himself very simple. </seg>
</p>
<p>
<seg id="3"> When he eventually leave sweat its doctrine so eagerly awaited, it emerged that he had Recopied carbon paper since the Iraq scenario of Bush three years ago. </seg>
<seg id="4"> Not content to use in the text several times the expression &quot;as in Iraq&quot;, he has not hesitated, that is, to use the title of the January 2007 speech by Bush as the title of his own speech: &quot;a new road before&quot; </seg>
</p>
<p>
<seg id="5"> At the same time, he has personally criticised the idea of Bush to send new reinforcements in Iraq consumed by the civil war as &quot;irresponsible and a disastrous decision in its consequences.&quot; </seg>
<seg id="6"> The following months have however shown that Bush ’ s strategy, which stemmed from recommendations of the campaigns commanders, was the only possible and likely success to the point that the newspapers at the moment do not speak at all of Iraq. </seg>
<seg id="7"> This has not improved the Bush reputation, objectively speaking, it has left to his successor a final situation much more favourable than we might hope. </seg>
<seg id="8"> Barack Obama hope that in Afghanistan, the miracle will happen </seg>
</p>
<p>
<seg id="9"> They are again the commanders of campaigns that have requested an increase of military contingent, including the Afghan operation commander, General Stanley Mccristal, who has severely criticised the reluctance of the White House despite the habits of subordination. </seg>
<seg id="10"> He asked 40 000 men in order to make the situation more favourable. </seg>
<seg id="11"> The President has hesitated for three months but in the absence of a better alternative, at least it has defrauded the general 10 000 soldiers. </seg>
<seg id="12"> He has managed to extricate the promise of additional 5 000 from the Europe, even if there were over 10 000. </seg>
</p>
<p>
<seg id="13"> This causes the most problems throughout the strategy of Obama seems to be its intention to withdraw military forces from Afghanistan within 18 months and to complete this whole process by three years. The doctrine of Obama brings more questions than it answers. </seg>
<seg id="14"> Many doubt the fact that an increase of half will bring the same fruit that progress in Iraq. </seg>
<seg id="15"> In spite of fratricidal wars in recent years, the Iraqi society is relatively well organised and its leaders honour the agreements. </seg>
</p>
<p>
<seg id="16"> The Afghan situation stands by the exact opposite - we cannot rely on person and no treaty is respected. </seg>
<seg id="17"> In these conditions, difficult to prepare Afghan security forces, used to change leader from day to day depending on what suits them. </seg>
<seg id="18"> The political institutions, although based formally remain that the smokescreen behind which will proliferate patriarchal ethnic relations. </seg>
<seg id="19"> It is particularly complex balancing the interests of various ethnic groups given the lack of clarity about the reports, which are still complicated by the Pakistani and Iranian influences. </seg>
<seg id="20"> Even the foundation of a &quot;state quick to act &apos;, which is the aim of the operation, does not seem to be very real. </seg>
<seg id="21"> The time horizon of the Obama strategy makes perplexed by his proactive. </seg>
<seg id="22"> In the past eight years, the situation in Afghanistan has deteriorated and is currently on the brink of chaos. </seg>
<seg id="23"> Only a heart purely romantic and out of reality can be persuaded that the small soldiers sent in the clamour of war in view of their &quot;quick return to the home&quot; will bring a real miracle. </seg>
</p>
<p>
<seg id="24"> From a political point of view, fix a date for the withdrawal of troops is purely irresponsible because the Taliban will see us as the indirect admission of defeat. </seg>
<seg id="25"> The last NATO summit showed that in military operations in Afghanistan is moving towards the negative. </seg>
<seg id="26"> The European political or do not want to explain to their electorate in what the security in Germany or Italy is linked to a war in the mountains of the Hindu Kush. </seg>
<seg id="27"> Another factor capable of radically alter of events related to Iran. </seg>
<seg id="28"> If the situation continues to deteriorate and the reinforced sanctions do not have effects on the Iranians, the Americans find themselves faced with the very difficult issue of a resolution of the problem by the use of military force. </seg>
<seg id="29"> It must be addressed by example when, according to Obama, America will the victorious withdrawal of troops in Afghanistan. </seg>
</p>
<p>
<seg id="30"> Each solution of this kind will however a dramatic reversal of the Afghan situation. </seg>
<seg id="31"> The only patch for Obama is the fact that it remains three years until the presidential elections and therefore there is still enough time to working on a new strategy, if it proves to be a flop. </seg>
</p>
</doc>
<doc docid="lidovky.cz/2009/12/10/75501" genre="nw">
<hl>
<seg id="1"> The leaders of the bank Goldman Sachs will receive more than premiums in cash </seg>
</hl>
<p>
<seg id="2"> The top leaders of the American bank Goldman Sachs employees will receive this year of cash premiums. </seg>
<seg id="3"> The company announced to respond to strong criticism about its practices. </seg>
</p>
<p>
<seg id="4"> The group of 30 leaders will receive shares instead of money, that they will not sell before five years. </seg>
